apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pesbuk
  annotations:
    ## Untuk menaikan batas upload file
    nginx.org/client-max-body-size: "10m"
    ## Memaksa jalan di https
spec:
  rules:
  - host: pesbuk.ibrahimsite.xyz
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: pesbuk
          servicePort: 80
