  
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    ## Untuk menaikan batas upload file
    nginx.org/client-max-body-size: "10m"
    ## Memaksa jalan di http
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: wordpress.ibrahimsite.xyz
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: wordpress
          servicePort: 80
